# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""move trial from team to user

Revision ID: 759add92bed8
Revises: 4ca01d2f892b
Create Date: 2019-12-18 09:36:47.015076

"""

# revision identifiers, used by Alembic.
revision = '759add92bed8'
down_revision = '4ca01d2f892b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ab_user', sa.Column('trial_used', sa.Boolean(), nullable=True))
    # op.drop_column('team_subscription', 'trial_used')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('team_subscription', sa.Column('trial_used', sa.BOOLEAN(), nullable=True))
    op.drop_column('ab_user', 'trial_used')
    # ### end Alembic commands ###
