# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""add num_request column to Plan

Revision ID: 8a5ee161c3fe
Revises: acfe1186b6dc
Create Date: 2019-10-10 12:41:50.136498

"""

# revision identifiers, used by Alembic.
revision = '8a5ee161c3fe'
down_revision = 'acfe1186b6dc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ab_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_request', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ab_plan', schema=None) as batch_op:
        batch_op.drop_column('num_request')

    # ### end Alembic commands ###
