# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""add_stripe_features

Revision ID: acfe1186b6dc
Revises: 6ce435a21d60
Create Date: 2019-10-10 10:14:23.407649

"""

# revision identifiers, used by Alembic.
revision = 'acfe1186b6dc'
down_revision = 'c6723e8fcea3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ab_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('stripe_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('team', sa.Column('stripe_pm_id', sa.String(length=64), nullable=True))
    op.add_column('team', sa.Column('stripe_user_id', sa.String(length=64), nullable=True))
    op.create_table('team_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('remain_count', sa.Integer(), nullable=True),
    sa.Column('stripe_sub_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['ab_plan.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_subscription')
    op.drop_table('ab_plan')
    op.drop_column('team', 'stripe_user_id')
    op.drop_column('team', 'stripe_pm_id')
    # ### end Alembic commands ###
