# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""record trial used

Revision ID: d8b84c20484e
Revises: f7928f0e549a
Create Date: 2019-10-18 16:16:13.764501

"""

# revision identifiers, used by Alembic.
revision = 'd8b84c20484e'
down_revision = 'f7928f0e549a'

from alembic import op
import sqlalchemy as sa


'''This version is deprecated and skipped'''

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('team_subscription', sa.Column('trial_used', sa.Boolean(), nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('team_subscription', 'trial_used')
    pass
    # ### end Alembic commands ###
