# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""add subscription end time and stripe event log

Revision ID: f7928f0e549a
Revises: 8a5ee161c3fe
Create Date: 2019-10-18 11:06:41.849225

"""

# revision identifiers, used by Alembic.
revision = 'f7928f0e549a'
down_revision = '8a5ee161c3fe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.create_table('stripe_event',
    # sa.Column('id', sa.String(length=64), nullable=False),
    # sa.Column('Type', sa.String(length=64), nullable=True),
    # sa.Column('Date', sa.DateTime(), nullable=True),
    # sa.Column('Object', sa.String(length=10000), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.add_column('team_subscription', sa.Column('end_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.drop_column('team_subscription', 'end_time')
    # op.drop_table('stripe_event')
    # ### end Alembic commands ###
